// Test harness: the parts of the e2e that are NOT the user (funding the fresh wallet, issuer
// actions, independent chain reads). Nothing here goes through the app's UI code paths.
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { Connection, Keypair, LAMPORTS_PER_SOL, PublicKey, SystemProgram, Transaction, sendAndConfirmTransaction } from "@solana/web3.js";
import { createAssociatedTokenAccountIdempotentInstruction, createMintToCheckedInstruction, getAssociatedTokenAddressSync } from "@solana/spl-token";
import * as sdk from "@stocklana/sdk";

const HERE = dirname(fileURLToPath(import.meta.url));

export interface E2eEnv {
  label: string; // "local, not devnet" or "devnet"
  cluster: "localnet" | "devnet";
  rpc: string; programId: string; shareMint: string; basket: string; usdc: string;
  legs: { symbol: string; mint: string }[];
  issuerKey: string; // fixture issuer key file (local: generated by setup; devnet: provided by Agent C)
  funderKey?: string; // devnet: pays SOL to the fresh wallet
}

export function loadEnv(): E2eEnv {
  const which = process.env.E2E_ENV ?? "local";
  if (which === "local") {
    const e = JSON.parse(readFileSync(join(HERE, ".local/env.json"), "utf8"));
    return { ...e, label: "local validator, not devnet", cluster: "localnet" };
  }
  const e = JSON.parse(readFileSync(join(HERE, "devnet/env.json"), "utf8"));
  return { ...e, label: "devnet", cluster: "devnet" };
}

export const conn = (env: E2eEnv) => new Connection(env.rpc, "confirmed");
export const loadKey = (p: string) => Keypair.fromSecretKey(Uint8Array.from(JSON.parse(readFileSync(p.replace(/^~/, process.env.HOME!), "utf8"))));

/** Every signature the run produces, in order, with who made it. */
export class RunRecord {
  readonly startedAt = new Date().toISOString();
  steps: { step: string; by: "test wallet (browser)" | "fixture issuer (harness)" | "funder (harness)"; signatures: string[]; slot?: number; note?: string; checks?: Record<string, unknown> }[] = [];
  screenshots: string[] = [];
  constructor(readonly env: E2eEnv, readonly wallet: string) {}
  add(s: RunRecord["steps"][number]) { this.steps.push(s); }
  write(outcome: "passed" | "failed", error?: string): string {
    const day = this.startedAt.slice(0, 10);
    const dir = join(HERE, "runs");
    mkdirSync(dir, { recursive: true });
    const file = join(dir, `${day}-${this.env.cluster}.json`);
    let prior: any[] = [];
    try { prior = JSON.parse(readFileSync(file, "utf8")).runs ?? []; } catch {}
    const run = {
      startedAt: this.startedAt, finishedAt: new Date().toISOString(), outcome, error,
      cluster: this.env.cluster, label: this.env.label,
      verification: this.env.cluster === "devnet" ? "devnet" : "local, not devnet — built, not verified",
      rpc: this.env.rpc, program: this.env.programId, basket: this.env.basket,
      wallet: { address: this.wallet, kind: "Stocklana Test Wallet: Wallet Standard test wallet generated fresh for this run (not Phantom)" },
      steps: this.steps, screenshots: this.screenshots,
    };
    writeFileSync(file, JSON.stringify({ runs: [...prior, run] }, null, 2));
    return file;
  }
}

/** Fund the fresh wallet: SOL, plus `amount` raw of every leg minted by the fixture issuer. */
export async function fundWallet(env: E2eEnv, wallet: PublicKey, amount: bigint, rec: RunRecord) {
  const c = conn(env);
  const issuer = loadKey(env.issuerKey);
  if (env.cluster === "localnet") {
    const s = await c.requestAirdrop(wallet, 5 * LAMPORTS_PER_SOL);
    await c.confirmTransaction(s, "confirmed");
    rec.add({ step: "airdrop 5 SOL to the fresh wallet (local faucet)", by: "funder (harness)", signatures: [s] });
  } else {
    const funder = loadKey(env.funderKey!);
    const s = await sendAndConfirmTransaction(c, new Transaction().add(SystemProgram.transfer({ fromPubkey: funder.publicKey, toPubkey: wallet, lamports: 0.2 * LAMPORTS_PER_SOL })), [funder]);
    rec.add({ step: "0.2 SOL to the fresh wallet", by: "funder (harness)", signatures: [s] });
  }
  const T22 = sdk.TOKEN_2022_PROGRAM_ID;
  const sigs: string[] = [];
  for (let i = 0; i < env.legs.length; i += 4) {
    const tx = new Transaction();
    for (const l of env.legs.slice(i, i + 4)) {
      const mint = new PublicKey(l.mint);
      const a = getAssociatedTokenAddressSync(mint, wallet, false, T22);
      tx.add(createAssociatedTokenAccountIdempotentInstruction(issuer.publicKey, a, wallet, mint, T22));
      tx.add(createMintToCheckedInstruction(mint, a, issuer.publicKey, amount, 9, [], T22));
    }
    sigs.push(await sendAndConfirmTransaction(c, tx, [issuer], { commitment: "confirmed" }));
  }
  rec.add({ step: `mint ${amount} raw of each of the seven fixture legs to the fresh wallet`, by: "fixture issuer (harness)", signatures: sigs });
}

/** Issuer action through the spl-token CLI (pause / resume). Returns the signature. */
export function issuerCli(env: E2eEnv, args: string[]): string {
  const out = execFileSync("spl-token", [...args, "-u", env.rpc, "--fee-payer", env.issuerKey, "--output", "json"], { encoding: "utf8" });
  const j = JSON.parse(out);
  const sig = j.signature ?? j.transactionData?.signature;
  if (!sig) throw new Error(`no signature from spl-token ${args[0]}: ${out}`);
  return sig;
}

// ------------------------------------------------ independent chain reads (not the app's code path)

export async function tokenAmount(env: E2eEnv, owner: PublicKey, mint: PublicKey, program = sdk.TOKEN_2022_PROGRAM_ID): Promise<bigint> {
  const a = getAssociatedTokenAddressSync(mint, owner, false, program);
  const r = await conn(env).getTokenAccountBalance(a, "confirmed").catch(() => null);
  return r ? BigInt(r.value.amount) : 0n;
}

/** Paused flag as decoded by the RPC node's own jsonParsed, not by the SDK. */
export async function mintPausedByRpc(env: E2eEnv, mint: PublicKey): Promise<boolean> {
  const r: any = await conn(env).getParsedAccountInfo(mint, "confirmed");
  const ext = r.value.data.parsed.info.extensions.find((e: any) => e.extension === "pausableConfig");
  return !!ext.state.paused;
}

export async function redemptionTickets(env: E2eEnv, owner: PublicKey) {
  const c = new sdk.BasketClient(conn(env), { programId: new PublicKey(env.programId), shareMint: new PublicKey(env.shareMint) });
  return c.redemptionTickets(owner);
}

export async function txOk(env: E2eEnv, sig: string): Promise<{ slot: number; logs: string[] }> {
  const t = await conn(env).getTransaction(sig, { maxSupportedTransactionVersion: 0, commitment: "confirmed" });
  if (!t) throw new Error(`transaction ${sig} not found`);
  if (t.meta?.err) throw new Error(`transaction ${sig} failed: ${JSON.stringify(t.meta.err)}`);
  return { slot: t.slot, logs: t.meta?.logMessages ?? [] };
}

export function toRaw(ui: string, decimals = 9): bigint {
  const t = ui.replace(/,/g, "").trim();
  const [i, f = ""] = t.split(".");
  return BigInt(i) * 10n ** BigInt(decimals) + BigInt((f + "0".repeat(decimals)).slice(0, decimals));
}
