// Generate fixtures/DIFF.md: every field difference between each fixture mint and the mainnet mint it
// mirrors, read live from both chains at stated slots. Regenerate, never hand-edit.
//
//   node scripts/fixtures/diff.ts --cluster devnet [--out fixtures/DIFF.md] [--check]
//
// --check exits 1 if any mirror check fails (extension set, fee now, pending fee, effective multiplier,
// paused, hook, default state, decimals), so a changed mainnet mint can't leave the fixtures silently stale.

import { join } from "node:path";
import { writeFileSync } from "node:fs";
import { extensions, feeSchedule, effectiveMultiplier, flatten, MAINNET_USDC } from "../../services/valuation/src/lib/token2022.ts";
import { cluster, arg, flag, loadRegistry, mainnet, rpcFor, REPO, nowIso } from "../lib/env.ts";

const c = cluster();
const reg = loadRegistry(c);
const rpc = rpcFor(c);
const main = mainnet();
const out = arg("out", c === "devnet" ? join(REPO, "fixtures", "DIFF.md") : join(REPO, "fixtures", ".local", "DIFF.md"))!;

/** Parsed mint with extensions keyed by name (so order differences don't misalign the field diff). */
function normalise(info: any) {
  const { extensions: list, ...base } = info;
  const ext: Record<string, any> = {};
  for (const e of list ?? []) ext[e.extension] = e.state ?? {};
  return { ...base, extensions: ext };
}

function classify(path: string, mainVal: string, fixVal: string, fixtureMint: string, mainMint: string): string {
  if (mainVal === mainMint && fixVal === fixtureMint) return "self-address (the mint's own address)";
  if (/withdrawWithheldAuthorityElgamalPubkey/.test(path)) return "ElGamal key (generated per issuer)";
  if (/uthority|delegate$/.test(path)) return "authority (fixture issuer stands in for PreStocks' Squads vault)";
  if (/TransferFee\.epoch$/.test(path)) return "fee schedule epoch (devnet epoch numbering)";
  if (/withheldAmount$/.test(path)) return "withheld fees (depends on transfer activity)";
  if (path === "supply") return "supply (fixture mints only what tests need)";
  if (/^extensions\.tokenMetadata\.(name|symbol|uri)$/.test(path)) return "metadata string";
  if (/newMultiplierEffectiveTimestamp$/.test(path)) return "multiplier timestamp (both in the past; effective value equal)";
  if (/scaledUiAmountConfig\.(multiplier|newMultiplier)$/.test(path)) return "MULTIPLIER FIELD";
  return "UNEXPECTED";
}

async function run() {
  const legs = reg.legs;
  const fixtureAddrs = legs.map((l: any) => l.mint).concat(reg.usdc ? [reg.usdc.mint] : []);
  const mainAddrs = legs.map((l: any) => l.mirror_of).concat([MAINNET_USDC]);
  const [fx, mn, fxEpoch, mnEpoch] = await Promise.all([rpc.accounts(fixtureAddrs), main.accounts(mainAddrs), rpc.epochInfo(), main.epochInfo()]);
  const [fxTime, mnTime] = await Promise.all([rpc.blockTime(fx.slot).catch(() => null), main.blockTime(mn.slot).catch(() => null)]);
  const now = Math.floor(Date.now() / 1000);
  const clusterName = c === "devnet" ? "devnet" : "local validator (127.0.0.1:8901)";

  const lines: string[] = [];
  const fail: string[] = [];
  const summary: string[] = [];
  const detail: string[] = [];
  const iso = (t: number | null) => (t ? new Date(t * 1000).toISOString().replace(".000Z", "Z") : "n/a");

  lines.push("# Fixture mints vs mainnet PreStocks mints");
  lines.push("");
  lines.push(`Generated by \`node scripts/fixtures/diff.ts --cluster ${c}\` at ${nowIso()}. **Do not edit by hand**; rerun the script.`);
  lines.push("");
  lines.push(`- **Mainnet** read at slot **${mn.slot}** (epoch ${mnEpoch.epoch}, block time ${iso(mnTime)}), \`getMultipleAccounts\` jsonParsed.`);
  lines.push(`- **Fixtures (${clusterName})** read at slot **${fx.slot}** (epoch ${fxEpoch.epoch}, block time ${iso(fxTime)}).`);
  lines.push(`- Fixture issuer (holds every fixture authority): \`${reg.fixture_issuer}\`.`);
  lines.push(`- \`--check\` mode exits non-zero when a mirror check below fails, so a mainnet change can't leave this file silently stale.`);
  lines.push("");

  summary.push("## Mirror checks");
  summary.push("");
  summary.push("Semantic comparisons at the two stated slots. Fees are compared as *in force now* and *pending*, because the two chains number epochs differently.");
  summary.push("");
  summary.push("| Leg | Fixture mint | Extension set | Fee now (main / fix) | Pending fee (main / fix) | Effective multiplier (main / fix) | Paused | Hook | Default state | Field diffs | Unexpected |");
  summary.push("|---|---|---|---|---|---|---|---|---|---|---|");

  legs.forEach((leg: any, i: number) => {
    const fa = fx.values[i], ma = mn.values[i];
    if (!fa || !ma) {
      fail.push(`${leg.symbol}: account missing (fixture ${Boolean(fa)}, mainnet ${Boolean(ma)})`);
      summary.push(`| ${leg.symbol} | \`${leg.mint}\` | MISSING | | | | | | | | |`);
      return;
    }
    const fi = fa.data.parsed.info, mi = ma.data.parsed.info;
    const fxn = Object.keys(extensions(fi)), mxn = Object.keys(extensions(mi));
    const onlyMain = mxn.filter((e) => !fxn.includes(e)), onlyFix = fxn.filter((e) => !mxn.includes(e));
    const setOk = !onlyMain.length && !onlyFix.length;
    const orderOk = setOk && fxn.join() === mxn.join();
    const ff = feeSchedule(fi, fxEpoch.epoch)!, mf = feeSchedule(mi, mnEpoch.epoch)!;
    const fm = effectiveMultiplier(fi, now), mm = effectiveMultiplier(mi, now);
    const fX = extensions(fi), mX = extensions(mi);
    const pend = (f: any) => (f.pending ? `${f.pending.bps} bps @${f.pending.effective_epoch}` : "none");
    const checks: [string, boolean][] = [
      ["extension set", setOk],
      ["decimals", fi.decimals === mi.decimals],
      ["fee now", ff.now_bps === mf.now_bps && ff.now_maximum_fee === mf.now_maximum_fee],
      ["pending fee bps", (ff.pending?.bps ?? null) === (mf.pending?.bps ?? null)],
      ["effective multiplier", Number(fm.effective) === Number(mm.effective)],
      ["paused", Boolean(fX.pausableConfig?.paused) === Boolean(mX.pausableConfig?.paused)],
      ["hook program", (fX.transferHook?.programId ?? null) === (mX.transferHook?.programId ?? null)],
      ["default state", fX.defaultAccountState?.accountState === mX.defaultAccountState?.accountState],
    ];
    for (const [name, ok] of checks) if (!ok) fail.push(`${leg.symbol}: ${name}`);
    const ok = (b: boolean) => (b ? "match" : "**DIFF**");

    // Field-by-field.
    const fflat = flatten(normalise(fi)), mflat = flatten(normalise(mi));
    const keys = [...new Set([...Object.keys(fflat), ...Object.keys(mflat)])].sort();
    const rows: string[] = [];
    let unexpected = 0, same = 0;
    for (const k of keys) {
      const a = mflat[k] ?? "(absent)", b = fflat[k] ?? "(absent)";
      if (a === b) { same++; continue; }
      let cls = classify(k, a, b, leg.mint, leg.mirror_of);
      if (cls === "MULTIPLIER FIELD") {
        // A stored/new multiplier field may differ while the effective value (checked above) is equal:
        // Token-2022 rolls an already-effective newMultiplier into the stored field when a later update
        // is scheduled (the multiplier-change scenario does this). Named explicitly; unexpected only if
        // the effective values differ.
        cls = Number(effectiveMultiplier(fi, now).effective) === Number(effectiveMultiplier(mi, now).effective)
          ? "**multiplier field differs, effective value equal** (left by the multiplier-change scenario; see fixtures/scenarios/multiplier-change.json)"
          : "UNEXPECTED";
      }
      if (cls === "UNEXPECTED") unexpected++;
      rows.push(`| \`${k}\` | \`${a}\` | \`${b}\` | ${cls === "UNEXPECTED" ? "**UNEXPECTED**" : cls} |`);
    }
    if (fa.space !== ma.space) rows.push(`| account size (bytes) | ${ma.space} | ${fa.space} | follows metadata string lengths |`);
    if (!orderOk && setOk) rows.push(`| extension TLV order | ${mxn.join(", ")} | ${fxn.join(", ")} | ordering only |`);
    if (unexpected) fail.push(`${leg.symbol}: ${unexpected} unexpected field difference(s)`);

    summary.push(`| ${leg.symbol} | \`${leg.mint}\` | ${setOk ? "identical" : `**DIFF** (only mainnet: ${onlyMain.join(", ") || "-"}; only fixture: ${onlyFix.join(", ") || "-"})`}${setOk && !orderOk ? " (order differs)" : ""} | ${mf.now_bps} / ${ff.now_bps} ${ok(checks[2][1])} | ${pend(mf)} / ${pend(ff)} ${ok(checks[3][1])} | ${mm.effective} / ${fm.effective} ${ok(checks[4][1])} | ${ok(checks[5][1])} | ${ok(checks[6][1])} | ${ok(checks[7][1])} | ${rows.length} | ${unexpected} |`);

    detail.push(`### ${leg.index}. ${leg.symbol}`);
    detail.push("");
    detail.push(`Mainnet \`${leg.mirror_of}\` vs fixture \`${leg.mint}\`. Extension set: mainnet [${mxn.join(", ")}]; fixture [${fxn.join(", ")}]. ${same} flattened fields are identical.`);
    detail.push("");
    detail.push("| Field | Mainnet | Fixture | Why it differs |");
    detail.push("|---|---|---|---|");
    detail.push(...rows);
    detail.push("");
  });

  // Fixture USDC vs mainnet USDC (classic SPL Token).
  if (reg.usdc) {
    const fa = fx.values[legs.length], ma = mn.values[legs.length];
    detail.push("### Fixture USDC");
    detail.push("");
    if (fa && ma) {
      const fi = fa.data.parsed.info, mi = ma.data.parsed.info;
      detail.push(`Mainnet \`${MAINNET_USDC}\` (owner \`${ma.owner}\`) vs fixture \`${reg.usdc.mint}\` (owner \`${fa.owner}\`).`);
      detail.push("");
      detail.push("| Field | Mainnet | Fixture | Why it differs |");
      detail.push("|---|---|---|---|");
      if (fa.owner !== ma.owner) { detail.push(`| token program | \`${ma.owner}\` | \`${fa.owner}\` | **UNEXPECTED** |`); fail.push("USDC: token program"); }
      if (fi.decimals !== mi.decimals) { detail.push(`| decimals | ${mi.decimals} | ${fi.decimals} | **UNEXPECTED** |`); fail.push("USDC: decimals"); }
      for (const k of ["mintAuthority", "freezeAuthority", "supply"]) {
        if (String(fi[k]) !== String(mi[k])) detail.push(`| \`${k}\` | \`${mi[k]}\` | \`${fi[k]}\` | ${k === "supply" ? "supply (fixture mints only what tests need)" : "authority (fixture issuer)"} |`);
      }
      detail.push("");
    } else {
      detail.push("MISSING account.");
      fail.push("USDC missing");
    }
  }

  lines.push(...summary, "");
  lines.push(fail.length ? `**Mirror checks failing:** ${fail.join("; ")}.` : "**All mirror checks pass.** Every remaining difference is listed per leg below, with the reason.");
  lines.push("");
  lines.push("## Every field difference, per leg");
  lines.push("");
  lines.push(...detail);
  writeFileSync(out, lines.join("\n"));
  console.log(`wrote ${out}: mainnet slot ${mn.slot}, ${c} slot ${fx.slot}; failing checks: ${fail.length ? fail.join("; ") : "none"}`);
  if (flag("check") && fail.length) process.exit(1);
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
