// Share maths from spec 01, as pure bigint functions over a snapshot of on-chain state.
// Must match spec/model/basket_model.py to the unit; test/math.test.ts replays vectors
// generated by that model (test/vectors/gen_vectors.py).
//
// Everything is raw units. No price appears here. Every division floors (vault's favour).
import { INDEX_ONE } from "./constants.js";
import { TransferFee, transferFee } from "./token2022.js";

export interface LegState {
  balance: bigint; // B_i, the vault's actual token amount (read live)
  accounted: bigint; // A_i
  claimUnits: bigint; // C_i
  pendingNorm: bigint; // P_i
  lossIndex: bigint; // L_i
  available: boolean;
  retired?: boolean;
}

export interface ObserveResult {
  leg: LegState;
  event: { kind: "ShortfallObserved"; expected: bigint; actual: bigint; lossIndex: bigint } | { kind: "SurplusObserved"; expected: bigint; actual: bigint } | null;
}

/** observe(i): the balance is the truth (spec 01, Observation). */
export function observe(leg: LegState): ObserveResult {
  const l = { ...leg };
  let event: ObserveResult["event"] = null;
  if (l.balance < l.accounted) {
    l.lossIndex = (l.lossIndex * l.balance) / l.accounted;
    event = { kind: "ShortfallObserved", expected: l.accounted, actual: l.balance, lossIndex: l.lossIndex };
  } else if (l.balance > l.accounted) {
    event = { kind: "SurplusObserved", expected: l.accounted, actual: l.balance };
  }
  l.accounted = l.balance;
  return { leg: l, event };
}

export function pendingActual(leg: LegState): bigint {
  return (leg.pendingNorm * leg.lossIndex) / INDEX_ONE;
}

/** owned_i = B_i − pending_i: what belongs to shares and claims. */
export function owned(leg: LegState): bigint {
  return leg.balance - pendingActual(leg);
}

export function denominator(leg: LegState, supply: bigint): bigint {
  return supply + leg.claimUnits;
}

/** Exact per-share ratio owned_i / (S + C_i); never pre-rounded. */
export function perShare(leg: LegState, supply: bigint): { num: bigint; den: bigint } {
  return { num: owned(leg), den: denominator(leg, supply) };
}

export class Refused extends Error {
  constructor(public readonly code: string) {
    super(code);
  }
}

/**
 * Shares minted for measured net deltas (in-kind deposit). `legs` is the state after observe
 * and BEFORE the deltas landed. m = min_i floor(Δ_i × denom_i / owned_i_before).
 */
export function sharesForDeltas(legs: LegState[], supply: bigint, deltas: bigint[]): bigint {
  let m: bigint | null = null;
  legs.forEach((leg, i) => {
    if (leg.retired) return;
    const own = owned(leg); // owned before the deposit == owned(after) − Δ_i
    if (own <= 0n) throw new Refused("LegEmpty");
    const cand = (deltas[i] * denominator(leg, supply)) / own;
    m = m === null || cand < m ? cand : m;
  });
  if (m === null) throw new Refused("LegEmpty");
  return m;
}

/** In-kind mint: gross per leg → measured net delta (fee now) → shares. Refused if any leg is unavailable. */
export function mintInKind(legs: LegState[], supply: bigint, gross: bigint[], fees: (TransferFee | { bps: number } | null)[], minShares = 0n) {
  const obs = legs.map((l) => (l.retired ? l : observe(l).leg));
  if (obs.some((l) => !l.retired && !l.available)) throw new Refused("LegUnavailable");
  const deltas = gross.map((g, i) => (obs[i].retired ? 0n : g - transferFee(g, fees[i])));
  const m = sharesForDeltas(obs, supply, deltas);
  if (m < (minShares > 1n ? minShares : 1n)) throw new Refused("SlippageExceeded");
  return { shares: m, deltas };
}

/** Ticket credit for a landed swap: floor(Δ_i × 10^18 / L_i). */
export function ticketNorm(delta: bigint, lossIndex: bigint): bigint {
  return (delta * INDEX_ONE) / lossIndex;
}

/**
 * finalize_deposit: `legs` is the state after observe, with the ticket's norms still inside P_i.
 * Mirrors the model: P_i is reduced first, then own = owned(after) − Δ_i.
 */
export function finalizeShares(legs: LegState[], supply: bigint, ticketNorms: bigint[]): { shares: bigint; deltas: bigint[] } {
  const deltas: bigint[] = [];
  const after = legs.map((leg, i) => {
    if (leg.retired) { deltas.push(0n); return leg; }
    deltas.push((ticketNorms[i] * leg.lossIndex) / INDEX_ONE);
    return { ...leg, pendingNorm: leg.pendingNorm - ticketNorms[i] };
  });
  let m: bigint | null = null;
  after.forEach((leg, i) => {
    if (leg.retired) return;
    const own = owned(leg) - deltas[i];
    if (own <= 0n) throw new Refused("LegEmpty");
    const cand = (deltas[i] * denominator(leg, supply)) / own;
    m = m === null || cand < m ? cand : m;
  });
  if (m === null) throw new Refused("LegEmpty");
  return { shares: m, deltas };
}

export type RedeemLegOutcome =
  | { action: "pay"; gross: bigint; fee: bigint; net: bigint }
  | { action: "claim"; units: bigint }
  | { action: "retired" };

/**
 * redeem(s, InKind): each available leg pays floor(s × owned_i / (S + C_i)) with S the supply
 * before the burn; each unavailable leg becomes a claim of s units. `legs` is pre-observe state.
 */
export function redeemInKind(legs: LegState[], supply: bigint, s: bigint, fees: (TransferFee | { bps: number } | null)[] = []): RedeemLegOutcome[] {
  if (s <= 0n || s > supply) throw new Refused("InsufficientShares");
  return legs.map((l, i) => {
    if (l.retired) return { action: "retired" } as const;
    const leg = observe(l).leg;
    if (!leg.available) return { action: "claim", units: s } as const;
    const gross = (s * owned(leg)) / (supply + leg.claimUnits);
    const fee = transferFee(gross, fees[i] ?? null);
    return { action: "pay", gross, fee, net: gross - fee } as const;
  });
}

/** State after a redeem, for chaining (tests and the local preview). */
export function applyRedeem(legs: LegState[], supply: bigint, s: bigint, outcomes: RedeemLegOutcome[]): { legs: LegState[]; supply: bigint } {
  const next = legs.map((l, i) => {
    if (l.retired) return l;
    const leg = observe(l).leg;
    const o = outcomes[i];
    if (o.action === "pay") return { ...leg, balance: leg.balance - o.gross, accounted: leg.accounted - o.gross };
    if (o.action === "claim") return { ...leg, claimUnits: leg.claimUnits + o.units };
    return leg;
  });
  return { legs: next, supply: supply - s };
}

/** settle_claim: floor(units × owned_i / (S + C_i)) after observe; refused while the leg is unavailable. */
export function settleClaim(l: LegState, supply: bigint, units: bigint, fee: TransferFee | { bps: number } | null = null) {
  const leg = observe(l).leg;
  if (!leg.available) throw new Refused("LegUnavailable");
  const gross = (units * owned(leg)) / denominator(leg, supply);
  const f = transferFee(gross, fee);
  return { gross, fee: f, net: gross - f };
}

/**
 * In-kind deposit sizing: the net delta per leg that mints at least `shares`, sized to the current
 * per-share composition: Δ_i = ceil(shares × owned_i / denom_i). Anything above the binding
 * leg's need stays in the vault for all holders (the UI discloses this residual).
 */
export function netDeltasForShares(legs: LegState[], supply: bigint, shares: bigint): bigint[] {
  return legs.map((l) => {
    if (l.retired) return 0n;
    const leg = observe(l).leg;
    const num = shares * owned(leg);
    const den = denominator(leg, supply);
    return (num + den - 1n) / den;
  });
}

/** Holder's current entitlement to leg i (display): floor(shares × owned_i / denom_i). */
export function holderAmount(leg: LegState, supply: bigint, shares: bigint): bigint {
  const d = denominator(leg, supply);
  return d === 0n ? 0n : (shares * owned(leg)) / d;
}

/** Fraction of a leg lost to an observed shortfall, as parts per million (display). */
export function shortfallPpm(expected: bigint, actual: bigint): bigint {
  if (expected === 0n) return 0n;
  return ((expected - actual) * 1_000_000n) / expected;
}
