// Test harness: the parts of the e2e that are NOT the user (funding the fresh wallet, issuer
// actions, independent chain reads). Nothing here goes through the app's UI code paths.
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { Connection, Keypair, LAMPORTS_PER_SOL, PublicKey, SystemProgram, Transaction } from "@solana/web3.js";

/** Send and confirm by HTTP polling (no websocket; the public devnet RPC limits connections per IP). */
export async function sendAndConfirmTransaction(c: Connection, tx: Transaction, signers: Keypair[], _opts?: unknown): Promise<string> {
  const { blockhash } = await c.getLatestBlockhash("confirmed");
  tx.recentBlockhash = blockhash;
  tx.feePayer = tx.feePayer ?? signers[0].publicKey;
  tx.sign(...signers);
  const raw = tx.serialize();
  const sig = await c.sendRawTransaction(raw, { skipPreflight: false, maxRetries: 5 });
  const st = await sdk.confirmByPolling(c, sig, raw);
  if (st.err) throw new Error(`transaction ${sig} failed: ${JSON.stringify(st.err)}`);
  return sig;
}
import { createAssociatedTokenAccountIdempotentInstruction, createBurnCheckedInstruction, createMintToCheckedInstruction, getAssociatedTokenAddressSync } from "@solana/spl-token";
import * as sdk from "@unlisted/sdk";

const HERE = __dirname; // CommonJS under Playwright here (the web package is not type: module)

export interface E2eEnv {
  label: string; // "local, not devnet" or "devnet"
  cluster: "localnet" | "devnet";
  rpc: string; programId: string; shareMint: string; basket: string; usdc: string;
  legs: { symbol: string; mint: string }[];
  issuerKey: string; // fixture issuer key file (local: generated by setup; devnet: provided by Agent C)
  funderKey?: string; // devnet: pays SOL to the fresh wallet
}

export function loadEnv(): E2eEnv {
  const which = process.env.E2E_ENV ?? "local";
  if (which === "local") {
    const e = JSON.parse(readFileSync(join(HERE, ".local/env.json"), "utf8"));
    return { ...e, label: "local validator, not devnet", cluster: "localnet" };
  }
  const e = JSON.parse(readFileSync(join(HERE, "devnet/env.json"), "utf8"));
  return { ...e, label: "devnet", cluster: "devnet" };
}

// One shared, polite connection per RPC URL: the public devnet RPC rate-limits new connections per IP.
const conns = new Map<string, Connection>();
export const conn = (env: E2eEnv) => {
  let c = conns.get(env.rpc);
  if (!c) {
    c = new Connection(env.rpc, { commitment: "confirmed", fetch: sdk.politeFetch({ concurrency: 1, minIntervalMs: env.cluster === "devnet" ? 250 : 0, maxRetries: 40,
      log: (m) => console.log(`[harness] ${m}`) }) as any, disableRetryOnRateLimit: true });
    conns.set(env.rpc, c);
  }
  return c;
};
export const loadKey = (p: string) => Keypair.fromSecretKey(Uint8Array.from(JSON.parse(readFileSync(p.replace(/^~/, process.env.HOME!), "utf8"))));

/** Every signature the run produces, in order, with who made it. */
export class RunRecord {
  readonly startedAt = new Date().toISOString();
  steps: { step: string; by: "test wallet (browser)" | "test wallet (harness)" | "fixture issuer (harness)" | "funder (harness)"; signatures: string[]; slot?: number; note?: string; checks?: Record<string, unknown> }[] = [];
  screenshots: string[] = [];
  outcome?: "passed" | "failed";
  error?: string;
  constructor(readonly env: E2eEnv, readonly wallet: string, readonly flow = "") {}
  add(s: RunRecord["steps"][number]) { this.steps.push(s); }
  write(outcome: "passed" | "failed", error?: string): string {
    this.outcome = outcome;
    if (error !== undefined) this.error = error;
    error = this.error;
    const day = this.startedAt.slice(0, 10);
    const dir = join(HERE, "runs");
    mkdirSync(dir, { recursive: true });
    const file = join(dir, `${day}-${this.env.cluster}${this.flow ? `-${this.flow}` : ""}.json`);
    let prior: any[] = [];
    try { prior = JSON.parse(readFileSync(file, "utf8")).runs ?? []; } catch {}
    const run = {
      startedAt: this.startedAt, finishedAt: new Date().toISOString(), outcome, error: error?.replace(/\u001b\[[0-9;]*m/g, ""),
      cluster: this.env.cluster, label: this.env.label,
      verification: this.env.cluster === "devnet" ? "devnet" : "local, not devnet — built, not verified",
      mutation: process.env.E2E_MUTATION ?? null, // set when this run is a deliberate-bug check (expected to fail)
      rpc: this.env.rpc, program: this.env.programId, basket: this.env.basket, programs: (this.env as any).programs ?? null,
      wallet: { address: this.wallet, kind: "Unlisted Test Wallet: Wallet Standard test wallet generated fresh for this run (not Phantom)" },
      valuationApi: (this.env as any).valuationApi ?? null,
      steps: this.steps, screenshots: this.screenshots,
    };
    // One entry per run: a later write (e.g. after returning SOL) replaces this run's entry.
    writeFileSync(file, JSON.stringify({ runs: [...prior.filter((r) => r.startedAt !== this.startedAt), run] }, null, 2));
    return file;
  }
}

/** Agent C's worktree: on devnet its scripts perform every fixture-issuer step (C owns that key). */
// Ported from app/e2e: since the 2026-09-25 consolidation, C's scripts live at the repo root on main.
const OPS_WORKTREE = process.env.E2E_OPS_WORKTREE ?? join(HERE, "..", "..", "..");

/** Runs one of C's scripts from C's worktree and returns its final JSON block. Signs with C's key, not ours. */
function opsScript(args: string[]): any {
  const out = execFileSync("node", args, { cwd: OPS_WORKTREE, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"], timeout: 600_000 });
  // The script's result is its last top-level JSON block ("{" ... "}" at column 0); other log lines may follow.
  const start = out.startsWith("{") && out.lastIndexOf("\n{") < 0 ? 0 : out.lastIndexOf("\n{") + 1;
  const end = out.indexOf("\n}", start);
  const json = JSON.parse(out.slice(start, end + 2));
  return { json, out };
}

/**
 * Fund the fresh wallet with SOL, every leg and fixture USDC.
 *  - local: this harness's own local issuer key (created by e2e/local/setup.ts);
 *  - devnet: Agent C's scripts/fixtures/fund-wallet.ts, run in C's worktree (C's key signs).
 */
export async function fundWallet(env: E2eEnv, wallet: PublicKey, amount: bigint, rec: RunRecord) {
  const c = conn(env);
  if (env.cluster === "devnet") {
    let sol = "0.05";
    if (env.funderKey) {
      const funder = loadKey(env.funderKey);
      if ((await c.getBalance(funder.publicKey)) > 0.1 * LAMPORTS_PER_SOL) {
        const s = await sendAndConfirmTransaction(c, new Transaction().add(SystemProgram.transfer({ fromPubkey: funder.publicKey, toPubkey: wallet, lamports: 0.08 * LAMPORTS_PER_SOL })), [funder]);
        rec.add({ step: "0.08 SOL to the fresh wallet from the app key", by: "funder (harness)", signatures: [s] });
        sol = "0";
      }
    }
    const { json } = opsScript(["scripts/fixtures/fund-wallet.ts", "--cluster", "devnet", "--wallet", wallet.toBase58(), "--usdc", "50", "--leg-usd", "20", "--sol", sol, "--actor", "app-e2e"]);
    rec.add({ step: `fund the fresh wallet: 50 fixture USDC, ~$20 of each leg${sol !== "0" ? `, ${sol} SOL` : ""} (Agent C's fund-wallet.ts)`, by: "fixture issuer (harness)",
      signatures: json.signatures, note: `legs: ${(json.legs ?? []).join(", ")}` });
    return;
  }
  const issuer = loadKey(env.issuerKey);
  const s = await c.requestAirdrop(wallet, 5 * LAMPORTS_PER_SOL);
  await c.confirmTransaction(s, "confirmed");
  rec.add({ step: "airdrop 5 SOL to the fresh wallet (local faucet)", by: "funder (harness)", signatures: [s] });
  const T22 = sdk.TOKEN_2022_PROGRAM_ID;
  const sigs: string[] = [];
  for (let i = 0; i < env.legs.length; i += 4) {
    const tx = new Transaction();
    for (const l of env.legs.slice(i, i + 4)) {
      const mint = new PublicKey(l.mint);
      const a = getAssociatedTokenAddressSync(mint, wallet, false, T22);
      tx.add(createAssociatedTokenAccountIdempotentInstruction(issuer.publicKey, a, wallet, mint, T22));
      tx.add(createMintToCheckedInstruction(mint, a, issuer.publicKey, amount, 9, [], T22));
    }
    sigs.push(await sendAndConfirmTransaction(c, tx, [issuer], { commitment: "confirmed" }));
  }
  const usdc = new PublicKey(env.usdc);
  const ua = getAssociatedTokenAddressSync(usdc, wallet, false, sdk.TOKEN_PROGRAM_ID);
  sigs.push(await sendAndConfirmTransaction(c, new Transaction().add(
    createAssociatedTokenAccountIdempotentInstruction(issuer.publicKey, ua, wallet, usdc, sdk.TOKEN_PROGRAM_ID),
    createMintToCheckedInstruction(usdc, ua, issuer.publicKey, 100_000_000n, 6, [], sdk.TOKEN_PROGRAM_ID)), [issuer], { commitment: "confirmed" }));
  rec.add({ step: `mint ${amount} raw of each of the seven fixture legs and 100 fixture USDC to the fresh wallet`, by: "fixture issuer (harness)", signatures: sigs });
}

/**
 * Issuer pause / resume of one leg's mint. Returns the signatures.
 *  - local: spl-token CLI with the local issuer key;
 *  - devnet: Agent C's scripts/scenarios/issuer.ts in C's worktree (records in fixtures/scenarios/pause-resume.json).
 */
export function issuerAction(env: E2eEnv, action: "pause" | "resume", symbol: string): string[] {
  if (env.cluster === "devnet") {
    const { json } = opsScript(["scripts/scenarios/issuer.ts", action, "--cluster", "devnet", "--symbol", symbol, "--actor", "app-e2e"]);
    return (json.steps as string[]).map((s) => /: (\w{60,}) @/.exec(s)?.[1]).filter(Boolean) as string[];
  }
  const mint = env.legs.find((l) => l.symbol === symbol)!.mint;
  return [issuerCli(env, [action, mint, "--pause-authority", env.issuerKey])];
}

/** Local issuer action through the spl-token CLI. Returns the signature. */
export function issuerCli(env: E2eEnv, args: string[]): string {
  const out = execFileSync("spl-token", [...args, "-u", env.rpc, "--fee-payer", env.issuerKey, "--output", "json"], { encoding: "utf8" });
  const j = JSON.parse(out);
  const sig = j.signature ?? j.transactionData?.signature;
  if (!sig) throw new Error(`no signature from spl-token ${args[0]}: ${out}`);
  return sig;
}

/**
 * Issuer seizure: BurnChecked from a basket vault by the permanent delegate.
 *  - local: built here, signed by the local issuer key;
 *  - devnet: Agent C's scripts/scenarios/issuer.ts seize (records in fixtures/scenarios/seizure.json).
 */
export async function issuerSeize(env: E2eEnv, symbol: string, vault: PublicKey, amount: bigint): Promise<string[]> {
  if (env.cluster === "devnet") {
    const { json } = opsScript(["scripts/scenarios/issuer.ts", "seize", "--cluster", "devnet", "--vault", vault.toBase58(), "--amount", amount.toString(), "--actor", "app-e2e"]);
    return (json.steps as string[]).map((s) => /: (\w{60,}) @/.exec(s)?.[1]).filter(Boolean) as string[];
  }
  const mint = new PublicKey(env.legs.find((l) => l.symbol === symbol)!.mint);
  const issuer = loadKey(env.issuerKey);
  const ix = createBurnCheckedInstruction(vault, mint, issuer.publicKey, amount, 9, [], sdk.TOKEN_2022_PROGRAM_ID);
  return [await sendAndConfirmTransaction(conn(env), new Transaction().add(ix), [issuer], { commitment: "confirmed" })];
}

/** Devnet: send the fresh wallet's leftover SOL back to the app key, so each run costs only fees and rent. */
/** Keeps each fresh test wallet's key in e2e/.local/wallets (gitignored) so its leftover SOL can be swept. */
export function saveTestWallet(w: Keypair) {
  const dir = join(HERE, ".local/wallets");
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, `${w.publicKey.toBase58()}.json`), JSON.stringify([...w.secretKey]));
}

export async function returnSol(env: E2eEnv, wallet: Keypair, rec: RunRecord) {
  if (env.cluster !== "devnet" || !env.funderKey) return;
  const c = conn(env);
  const to = loadKey(env.funderKey).publicKey;
  const bal = await c.getBalance(wallet.publicKey, "confirmed");
  if (bal <= 10_000) return;
  const s = await sendAndConfirmTransaction(c, new Transaction().add(SystemProgram.transfer({ fromPubkey: wallet.publicKey, toPubkey: to, lamports: bal - 5_000 })), [wallet], { commitment: "confirmed" });
  rec.add({ step: `return ${(bal - 5_000) / LAMPORTS_PER_SOL} SOL to the app key`, by: "test wallet (harness)", signatures: [s] });
  rec.write(rec.outcome ?? "passed");
}

// ------------------------------------------------ independent chain reads (not the app's code path)

export async function tokenAmount(env: E2eEnv, owner: PublicKey, mint: PublicKey, program = sdk.TOKEN_2022_PROGRAM_ID): Promise<bigint> {
  const a = getAssociatedTokenAddressSync(mint, owner, false, program);
  const r = await conn(env).getTokenAccountBalance(a, "confirmed").catch(() => null);
  return r ? BigInt(r.value.amount) : 0n;
}

/** Several token balances in ONE request (getMultipleParsedAccounts: amounts decoded by the RPC node). */
export async function tokenAmounts(env: E2eEnv, owner: PublicKey, mints: PublicKey[], program = sdk.TOKEN_2022_PROGRAM_ID): Promise<bigint[]> {
  const atas = mints.map((m) => getAssociatedTokenAddressSync(m, owner, false, program));
  const r = await conn(env).getMultipleParsedAccounts(atas, { commitment: "confirmed" });
  return r.value.map((a: any) => (a ? BigInt(a.data.parsed.info.tokenAmount.amount) : 0n));
}

/**
 * Scaled-UI multiplier per mint as decoded by the RPC node's jsonParsed (one request), and the one in
 * effect at the current cluster block time. Mints without the extension give null.
 */
export async function multipliersByRpc(env: E2eEnv, mints: PublicKey[]): Promise<({ stored: number; effective: number; next: number; at: number } | null)[]> {
  const c = conn(env);
  const r = await c.getMultipleParsedAccounts(mints, { commitment: "confirmed" });
  const now = await c.getBlockTime(r.context.slot).catch(() => null) ?? Math.floor(Date.now() / 1000);
  return r.value.map((a: any) => {
    const e = a?.data?.parsed?.info?.extensions?.find((x: any) => x.extension === "scaledUiAmountConfig");
    if (!e) return null;
    const stored = Number(e.state.multiplier), next = Number(e.state.newMultiplier), at = Number(e.state.newMultiplierEffectiveTimestamp);
    return { stored, next, at, effective: now >= at ? next : stored };
  });
}

/** Paused flag as decoded by the RPC node's own jsonParsed, not by the SDK. */
export async function mintPausedByRpc(env: E2eEnv, mint: PublicKey): Promise<boolean> {
  const r: any = await conn(env).getParsedAccountInfo(mint, "confirmed");
  const ext = r.value.data.parsed.info.extensions.find((e: any) => e.extension === "pausableConfig");
  return !!ext.state.paused;
}

/** Transfer fee bps in force now, as decoded by the RPC node's jsonParsed. */
export async function feeBpsByRpc(env: E2eEnv, mint: PublicKey): Promise<number> {
  const c = conn(env);
  const [r, epoch]: any = await Promise.all([c.getParsedAccountInfo(mint, "confirmed"), c.getEpochInfo("confirmed")]);
  const tf = r.value.data.parsed.info.extensions.find((e: any) => e.extension === "transferFeeConfig").state;
  return epoch.epoch >= tf.newerTransferFee.epoch ? tf.newerTransferFee.transferFeeBasisPoints : tf.olderTransferFee.transferFeeBasisPoints;
}

export async function depositTickets(env: E2eEnv, owner: PublicKey) {
  const c = new sdk.BasketClient(conn(env), { programId: new PublicKey(env.programId), shareMint: new PublicKey(env.shareMint) });
  return c.depositTickets(owner);
}

export async function redemptionTickets(env: E2eEnv, owner: PublicKey) {
  const c = new sdk.BasketClient(conn(env), { programId: new PublicKey(env.programId), shareMint: new PublicKey(env.shareMint) });
  return c.redemptionTickets(owner);
}

export async function txOk(env: E2eEnv, sig: string): Promise<{ slot: number; logs: string[] }> {
  const t = await conn(env).getTransaction(sig, { maxSupportedTransactionVersion: 0, commitment: "confirmed" });
  if (!t) throw new Error(`transaction ${sig} not found`);
  if (t.meta?.err) throw new Error(`transaction ${sig} failed: ${JSON.stringify(t.meta.err)}`);
  return { slot: t.slot, logs: t.meta?.logMessages ?? [] };
}

/** The deposit ticket a transaction opened: the third account of its first instruction to the program. */
export async function ticketOpenedBy(env: E2eEnv, sig: string): Promise<PublicKey> {
  const t = await conn(env).getTransaction(sig, { maxSupportedTransactionVersion: 0, commitment: "confirmed" });
  if (!t) throw new Error(`transaction ${sig} not found`);
  const keys = t.transaction.message.getAccountKeys({ accountKeysFromLookups: t.meta?.loadedAddresses });
  const program = new PublicKey(env.programId);
  const first = t.transaction.message.compiledInstructions.find((i) => keys.get(i.programIdIndex)!.equals(program));
  if (!first) throw new Error(`no basket instruction in ${sig}`);
  return keys.get(first.accountKeyIndexes[2])!;
}

/** Token accounts a ticket PDA still owns, per token program, as the RPC node reports them (not the SDK). */
export async function ticketOwnedByRpc(env: E2eEnv, ticket: PublicKey): Promise<{ token: string[]; token2022: string[] }> {
  const c = conn(env);
  const [a, b] = await Promise.all([sdk.TOKEN_PROGRAM_ID, sdk.TOKEN_2022_PROGRAM_ID].map((programId) => c.getTokenAccountsByOwner(ticket, { programId }, "confirmed")));
  return { token: a.value.map((x) => x.pubkey.toBase58()), token2022: b.value.map((x) => x.pubkey.toBase58()) };
}

export function toRaw(ui: string, decimals = 9): bigint {
  const t = ui.replace(/,/g, "").trim();
  const [i, f = ""] = t.split(".");
  return BigInt(i) * 10n ** BigInt(decimals) + BigInt((f + "0".repeat(decimals)).slice(0, decimals));
}
